home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.home_view, name="index"),
]

job/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('job', all_job, name="all_job"),
    path('job/register', JobCreate.as_view(), name='JobCreate'),
    path('job/<jcat>', job_cat, name='job_cat'),
    path('job/<jowner>/<jcat>/<jid>', job, name='single_job'),
]

movasat/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from movasat import settings
urlpatterns = [
    path('madmin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('course/', include('lms.urls')),
    path('', include('job.urls')),
    path('', include('madadyar.urls')),
    path('', include('challenge.urls')),
    path('', include('harkat.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

admin.site.site_header = ' پنل مدیریت '
admin.site.site_title = ' پنل مدیریت '
admin.site.index_title = 'پنل مدیریت'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse
from django_jalali.db import models as jmodels
from job.models import Skills
from location_field.models.plain import PlainLocationField
from Cities.models import City


class UserDetail(AbstractUser):
    otp = models.SmallIntegerField(default=0, editable=False)
    tel = models.CharField(max_length=11, null=False, blank=False, verbose_name="شماره تماس")
    Avatar = models.ImageField(upload_to="files/avatar/", verbose_name="آواتار")
    melli = models.CharField(max_length=10, unique=True, null=False, blank=False, verbose_name="کد ملی")
    City = models.ForeignKey(City, on_delete=models.CASCADE, null=True, verbose_name="شهر")
    birth = jmodels.jDateField(blank=True, null=True, verbose_name="تاریخ تولد")
    skills = models.ForeignKey(Skills, on_delete=models.CASCADE, blank=True, null=True, verbose_name="تخصص ها")
    is_job_finder = models.BooleanField(default=False, verbose_name="در جستجوی کار")

    class Meta:
        verbose_name = "اطلاعات کاربری"
        verbose_name_plural = "اطلاعات کاربری"

    def __str__(self):
        return f"{self.get_full_name()}  «{self.username}»"


class MadadKar(models.Model):
    user = models.OneToOneField(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="حساب کاربری")
    TYPE_CHOICES = (
        ('j', 'گروه جهادی'),
        ('k', 'موسسه خیریه'),
        ('n', 'سازمان مردم نهاد'),
    )
    GroupType = models.CharField(choices=TYPE_CHOICES, max_length=1, verbose_name="نوع")
    Name = models.CharField(max_length=110, verbose_name="نام موسسه")
    RegisterCode = models.PositiveBigIntegerField(verbose_name="کد ثبت موسسه",
                    help_text="توجه کنید که تمامی حقوق مربوط به حرکت های ثبتی توسط شما متوجه این موسسه خواهد بود")
    Cover = models.ImageField(upload_to="files/cover/", verbose_name="کاور")
    Avatar = models.ImageField(upload_to="files/avatar/", verbose_name="آواتار")
    Bio = models.TextField(verbose_name="توضیحات")
    City = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="شهر")
    Location = PlainLocationField(default='29.5,52.5', zoom=4, blank=True, verbose_name='موقعیت مکانی')
    Address = models.TextField(verbose_name="آدرس")
    Url = models.URLField(verbose_name="وبسایت", blank=True)
    Tel = models.CharField(max_length=11, verbose_name="شماره تلفن")
    Eita = models.URLField(verbose_name="لینک صفحه در ایتا", blank=True)
    Rubika = models.URLField(verbose_name="لینک صفحه در روبیکا", blank=True)
    Bale = models.URLField(verbose_name="لینک صفحه در بله", blank=True)

    class Meta:
        verbose_name = "مددکار"
        verbose_name_plural = "مددکار ها"

    def __str__(self):
        name_val = dict(self.TYPE_CHOICES).get(self.GroupType)
        return f"{name_val}  «{self.Name}»"

    def group_name(self):
        name_val = dict(self.TYPE_CHOICES).get(self.GroupType)
        return name_val

    def get_absolute_url(self):
        # return reverse("get_profile", kwargs={"user": self.user.username, })
        return reverse("get_profile", kwargs={"user": UserDetail.objects.get(id=self.user_id).username, })

    def get_edit_url(self):
        edit_url = reverse("admin:%s_%s_change" % (self._meta.app_label, self._meta.model_name), args=(self.id,))
        if edit_url:
            return edit_url
        else:
            self.get_absolute_url()

home/models.py
from ckeditor.fields import RichTextField
from django.db import models

# Create your models here.


class Box(models.Model):
    title = models.CharField(max_length=202, null=False, blank=False, verbose_name="عنوان")
    location = models.SlugField(unique=True, verbose_name="محل قرارگیری")
    photo = models.ImageField(upload_to='files/', null=True, blank=True, verbose_name="تصویر")
    content = RichTextField(blank=True, verbose_name="محتوا")

    class Meta:
        verbose_name = "باکس‌ها"
        verbose_name_plural = "باکس‌ها"

    def __str__(self):
        return self.title

home/views.py
import home.models
import madadyar.models
from challenge.models import Forum, Divar
from harkat.models import CrowdFunding, Project
from job.models import Job
from lms.models import Course
from madadyar.models import JahadActivity
from django.shortcuts import render

# Create your views here.


def home_view(request):
    projects_data = []
    for jad in JahadActivity.objects.all():
        projects_data.append({
            'id': jad.id,
            'title': jad.title,
            'lat': jad.location.split(",")[0],
            'lng': jad.location.split(",")[1],
            'photo': jad.MadadKar.Avatar.url,
            'icon': "static/assets/icons/heart_marker.png",
            'type': "JahadActivity",
            'date': jad.MadadJoo.RegisterDate,
            'url': jad.MadadKar.get_absolute_url(),#@todo jad.get_absolute_url,
        })

    for cd in CrowdFunding.objects.exclude(Location="").all():
        projects_data.append({
            'id': cd.id,
            'title': cd.Title,
            'lat': cd.Location.split(",")[0],
            'lng': cd.Location.split(",")[1],
            'photo': cd.Picture.url,
            'icon': "static/assets/icons/crowd_marker.png",
            'type': "CrowdFunding",
            'date': cd.date,
            'url': cd.get_absolute_url(),
        })


    for pd in Project.objects.exclude(location="").all():
        projects_data.append({
            'id': pd.id,
            'title': pd.name,
            'lat': pd.location.split(",")[0],
            'lng': pd.location.split(",")[1],
            'photo': pd.thumbnail.url,
            'icon': "static/assets/icons/project_marker.png",
            'type': "Project",
            'date': pd.date,
            'url': pd.madadkar.get_absolute_url(),
        })

    # for p in projects_data:
    #     print(p.get("title"))
    harkat_box = ""
    if home.models.Box.objects.filter(location="harkat").exists():
        harkat_box = home.models.Box.objects.filter(location="harkat").get()

    context = {
        'harkat': CrowdFunding.objects.all(),
        'course': Course.objects.all(),
        'forum': Forum.objects.all(),
        'divar': Divar.objects.filter().all(),
        'divars': Divar.objects.filter(Type=0).all(),
        'amanat': Divar.objects.filter(Type=1).all(),
        'jobs': Job.objects.all(),
        'map': projects_data,
        'box': {
            'harkat': harkat_box,
        },
        'statistics': {
            'lms': f"{Course.objects.all().count():,}",
            'harkat': f"{CrowdFunding.objects.all().count():,}",
            'madadyar': f"{JahadActivity.objects.all().count():,}",
            'forum': f"{Forum.objects.all().count():,}",
            # 'job': f"{Job.objects.all().count():,}",
        },
    }
    return render(request, 'home.html', context)

home/templates/partial/madadkar_profile.html
{% load saelozahra_tag %}
<div class="section cc-home-wrap">
    <div class="intro-header cc-subpage" style="width: 100%; height: 410px; background-image: url('{% if data.Cover %}{{ data.Cover.url }}{% else %}/static/img/bgIMG4.svg{% endif %}'); background-size: cover; background-position: center; background-repeat: no-repeat; margin-bottom: auto; text-align: center">

    </div>
    <div class="row" style="height: 202px; margin-top: -101px; margin-bottom: 33px">
        <img class="avatar-pic" src="{% if data.Avatar %}{{ data.Avatar.url }}{% else %}/static/satrap-logo-light.png{% endif %}" >
        </div>
    <div class="about-story-wrap">
    <h3>
        {{ data.get_GroupType_display }} : {{ data.Name }}
    </h3>
        <div class="divider"></div>
        <div class="container">
            <p class="paragraph-light">
                {{ data.Bio|safe }}
            </p>

            <br style="clear: both">
            <br style="clear: both">
            <div class="row crowd_funding">
                <br style="clear: both">
                <br style="clear: both">
                <h2 class="title_line"><span class="tc">حرکت‌های جهادی</span></h2>
                <br style="clear: both">
                <br style="clear: both">
                <br style="clear: both">
                <br style="clear: both">
                <div class="container two-col">
                    {% for hi in harkat %}
                        {% include "harkat_item.html" with h=hi %}
                    {% endfor %}
                </div>
            </div>


        </div>
    </div>
    <div class="container">

        <br style="clear: both">
        <br style="clear: both">
        <br style="clear: both">
        <h2 class="title_line"><span class="tc">خط زمان پروژه ها</span></h2>
        <br style="clear: both">
        <br style="clear: both">

        <div class="row" dir="ltr">

            {% for p in project %}
                <div id="tooltip_p{{ p.id }}" class="fl hide" style="width: 555px;max-height: 188px;" >
                    <div class="taj fl" style="width: 70%; padding-right:14px ">
                        <h5 style="margin-top: -20px">{{ p.date|rplc }}  <i class="tcd mdi mdi-hand-heart"></i>  {{ p.ProjectCat }}</h5>
                        <h3>{{ p.name }}</h3>
                        {{ p.description|safe|truncatechars_html:202 }}
                    </div>
                    <img src="{{ p.thumbnail.url }}" alt="" class="br fr" style="width: 30%;max-height: 100%;">
                </div>
            {% endfor %}
            <div class="timeline">
                {% for p in project %}
                    <div class="timeline__event animated fadeInUp delay-1s tooltip timeline__event--type{{ p.ProjectCat.CType }}" data-tipped-options="inline: 'tooltip_p{{ p.id }}'">
                        <div class="timeline__event__icon">
                            <i class="mdi mdi-charity"></i>
                        </div>
                        <div class="timeline__event__date" style="background-image: url('{% if p.thumbnail %}{{ p.thumbnail.url }}{% endif %}')">
                            {{ p.date|rplc }}
                        </div>
                        <div class="timeline__event__content">
                            <div class="timeline__event__title tar">
                                {{ p.name }}
                            </div>
                            <div class="timeline__event__description tar">
                                {{ p.description|slice:313|safe|striptags }}...
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>